# Generated by Django 2.2.4 on 2024-09-27 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('request_number', models.CharField(max_length=20)),
                ('residence', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriber_created_by', to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriber_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='تم التعديل بواسطة')),
            ],
        ),
    ]
