# Generated by Django 2.2.4 on 2024-09-27 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='address',
            new_name='residence',
        ),
    ]
