# Generated by Django 2.2.4 on 2024-10-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20240928_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='id_number',
            field=models.CharField(max_length=20, verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='request',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='رقم الهاتف '),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_number',
            field=models.CharField(max_length=20, verbose_name='رقم الطلب '),
        ),
        migrations.AlterField(
            model_name='request',
            name='residence',
            field=models.CharField(max_length=200, verbose_name='مكان السكن '),
        ),
        migrations.AlterField(
            model_name='request',
            name='subscriber_name',
            field=models.CharField(max_length=100, verbose_name='اسم المشترك '),
        ),
    ]
