# Generated by Django 2.2.4 on 2024-10-05 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_auto_20241005_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='migration_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الترحيل'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='migration_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriber_migration_by', to=settings.AUTH_USER_MODEL, verbose_name='تم الترحيل بواسطة'),
        ),
    ]
